title = "Toronto Nepali Film Festival"
baseURL = "http://tnff.ca/"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
publishDir = "docs"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/favicon.ico"
  description = "Toronto Nepali Film Festival"
  facebook = "https://www.facebook.com/TorontoNepaliFilmFestival/"
  twitter = "https://twitter.com/tnffcanada"
  instagram = "https://instagram.com/tnffcanada"
  youtube = "https://www.youtube.com/user/tnffcanada"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 3
  body_classes = "athelas bg-near-white"
